language: android

android:
  components:
    - build-tools-22.0.1
    - android-16

jdk:
  - oraclejdk7
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "gsbIdYPijtSVfgAeCnAT+qhPGh9vJVsWFLImU0XuvjDV9pNQ+HxL/XQndL0CzIMji+PGdtD1Oeo0Kon/ynJ8wyagk8+VDD1glsBOlr87wdn3sd+LhdxNTFM4XYmw3Wq6i5Hs+HwtoixWRLS64dsEvNrf07XYQN0VbdLmqhytCcs="
    - secure: "g7JbR/gRci59QplZKq5Xh85XMbdcBD97knKEG46Yiyfay3K+WThIPHer5FPOV65lgM5c7zw2uTAqpOFhLUtzr1dbGZwhLrpkGX5r07UmV4ByoOMaV5Cb34Lay53BqZe7AHCtn66csaZMTJsQvGD/7XrE+UuX5sktI3RffFPhtic="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
